[FileDialog]
history=file:///home/herbobra/Coding/Coding/Notes/classes/Варя, file:///home/herbobra/Coding/Coding/Notes/classes/Руслан, file:///home/herbobra/Coding/Coding/ibls, file:///home/herbobra/Coding/Coding/Notes/work/IBLS, file:///home/herbobra/Coding/Coding/Classes, file:///home/herbobra
lastVisited=file:///home/herbobra
qtVersion=6.10.2
shortcuts=file:, file:///home/herbobra
sidebarWidth=118
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\x3\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\xad\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x2i\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0V\0\0\0\x1\0\0\0\0\0\0\0\x98\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)
viewMode=Detail
